### ISSUE TITLE
Hashable `eqx.Module`

### ISSUE THREAD

**Issue by bhoov** [patrick-kidger/equinox#11]
Thank you for this fantastic library -- I love the transparency of the systems you can build when everything is just a python datastructure.

As it stands, `eqx.Modules` do not have a way of being hashed. This makes decorating methods with `@jax.jit` impossible, and it complains:

```
ValueError: Non-hashable static arguments are not supported. An error occured while trying to hash an object of type <class '__main__.SimpleModule'>, SimpleModule(layers=[NeuronLayer(lagrangian=<function SimpleModule.__init__.<locals>.<lambda> at 0x7f818447b160>, shape=(32,), tau=1.0), NeuronLayer(lagrangian=Softmax(beta=1), shape=(500,), tau=0.0)], synapses=[DenseSynapse(W=DeviceArray([[ 1.1177216 , -0.85337347,  0.62181216, ...,  0.47079483,
               2.1223438 ,  0.11009306],
             [-0.19882406, -0.58834153,  0.27299452, ...,  0.3560427 ,
              -1.3553874 , -0.64876467],
             [-0.27144387, -0.24926849,  1.7452046 , ...,  0.90979475,
              -0.37605172, -0.30193415],
             ...,
             [ 0.25044632, -0.96083486,  0.18758047, ...,  0.82221097,
               0.73630685, -0.7022106 ],
             [-1.0072463 , -0.30353332,  1.412912  , ..., -1.0664191 ,
              -1.1468811 ,  0.5145061 ],
             [-0.7490296 ,  2.1055915 , -1.5650765 , ...,  1.9068209 ,
               0.04990109,  0.2296551 ]], dtype=float32))], connections=[(0, 1, 0)]). The error was:
TypeError: unhashable type: 'SimpleModule'
```

I was curious if there is anything preventing `eqx.Modules` from providing a default hash function. They are, after all, just data containers with a few methods attached to them.

**Comment by patrick-kidger** [comment]
Thank you for the positive review!

So judging from your error message, I don't think it'll be possible to hash `eqx.Module`s for your use case. The reason is that you have a JAX array as part of the PyTree, and JAX arrays aren't hashable.

(Theoretically I think it should be fine to define hashing `eqx.Module`s that feature no JAX arrays, but that's a very uninteresting/unusual edge case for obvious reasons.)

It should be fine to JIT methods (indeed I do it all the time); you just need to make sure that the `self` parameter handles static vs tracing appropriately, typically via a filtered transformation.

```python
import functools as ft
import equinox as eqx

class MyModule(eqx.Module):
    @ft.partial(eqx.jitf, filter_fn=eqx.is_array)
    def __call__(self, x):
        ...
```

Substituting `filter_fn` for whatever criterion you need, of course. (Or a `filter_tree` if you need really fine-grained control.) I find that `is_array` is usually the desired behaviour though.

(It sounds like you're doing `@ft.partial(jax.jit, static_argnums=0)` instead? This would produce the error message you've given.)

**Comment by bhoov** [comment]
(Good eye -- yes, I did the `@ft.partial(jax.jit, static_argnums=0)` command you mention, thanks for filling in that gap in my request)

Sweet yes, this is what I was looking for. I had a misconception about how JIT was supposed to work regarding static arguments. Thanks for clearing it up!
