### ISSUE TITLE
MultiheadAttention fails with jit

### ISSUE THREAD

**Issue by Honyant** [patrick-kidger/equinox#116]
I'm trying to apply jit on MultiheadAttention, but it fails with the error at the bottom.

Is this intended behavior and do I need to amend my code to make it work, or is this a bug?

Code to reproduce:

```python
import jax
from jax import jit
from equinox import nn

key=jax.random.PRNGKey(1)
x=jax.random.uniform(key,shape=(128,128))
fn = nn.MultiheadAttention(num_heads=4,query_size=128, key=key)
print(fn(x,x,x))#no error

jitfn=jit(fn)
jitfn(x,x,x)#error
```

Jitting anything else works fine, as shown below, so I'm really not sure whats going on here.

```python
key=jax.random.PRNGKey(1)
x=jax.random.uniform(key,shape=(512,512))
fn=nn.Linear(512,512,key=key)
jf=jax.jit(jax.vmap(fn))
print(jf(x))#no error
```

Using:
jax==0.3.13
jaxlib==0.3.10
TPUv3-8

Error:
 /usr/bin/python3 /home/user/test.py
[[-0.2663889  -0.27051717  0.30525076 ... -0.02164279 -0.2024431
  -0.0249927 ]
 [-0.2666377  -0.2701754   0.30496052 ... -0.02156474 -0.20202553
  -0.02540369]
 [-0.26633754 -0.269254    0.3052082  ... -0.02223095 -0.20229273
  -0.02446468]
 ...
 [-0.2664026  -0.27016145  0.3046164  ... -0.02186189 -0.20281462
  -0.02462736]
 [-0.26611388 -0.27089423  0.30526304 ... -0.02130662 -0.20182835
  -0.02445403]
 [-0.26638734 -0.27083722  0.305067   ... -0.02205642 -0.2022052
  -0.02486622]]
Traceback (most recent call last):
  File "/home/user/test.py", line 11, in <module>
    jitfn(x,x,x)#error
  File "/home/user/.local/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/jax/_src/api.py", line 473, in cache_miss
    out_flat = xla.xla_call(
  File "/home/user/.local/lib/python3.8/site-packages/jax/core.py", line 1765, in bind
    return call_bind(self, fun, *args, **params)
  File "/home/user/.local/lib/python3.8/site-packages/jax/core.py", line 1781, in call_bind
    outs = top_trace.process_call(primitive, fun_, tracers, params)
  File "/home/user/.local/lib/python3.8/site-packages/jax/core.py", line 678, in process_call
    return primitive.impl(f, *tracers, **params)
  File "/home/user/.local/lib/python3.8/site-packages/jax/_src/dispatch.py", line 182, in _xla_call_impl
    compiled_fun = _xla_callable(fun, device, backend, name, donated_invars,
  File "/home/user/.local/lib/python3.8/site-packages/jax/linear_util.py", line 273, in memoized_fun
    cache = fun_caches.setdefault(fun.f, {})
  File "/usr/lib/python3.8/weakref.py", line 476, in setdefault
    return self.data.setdefault(ref(key, self._remove),default)
  File "/home/user/.local/lib/python3.8/site-packages/equinox/module.py", line 232, in __hash__
    return hash(tuple(jax.tree_leaves(self)))
jax._src.traceback_util.UnfilteredStackTrace: TypeError: unhashable type: 'DeviceArray'

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/test.py", line 11, in <module>
    jitfn(x,x,x)#error
  File "/usr/lib/python3.8/weakref.py", line 476, in setdefault
    return self.data.setdefault(ref(key, self._remove),default)
  File "/home/user/.local/lib/python3.8/site-packages/equinox/module.py", line 232, in __hash__
    return hash(tuple(jax.tree_leaves(self)))
TypeError: unhashable type: 'DeviceArray'

**Comment by patrick-kidger** [comment]
This is expected; you need to modify your code.

In your first code snippet, `fn` is a `MultiheadAttention`, which is a PyTree (as is any other Equinox module). Meanwhile, JAX assumes that any callable you're trying to jit is hashable. Indeed usually you're jitting/hashing a regular Python function -- not a callable PyTree.

The reason the second code snippet works is because `jax.vmap` creates a new Python function on the fly for you -- corresponding to the batched version of the input function you pass in -- and that's just a regular Python function. And regular Python functions are hashable and thus jittable.

So, how to fix things? The simplest/best answer is use `eqx.filter_jit` instead of `jax.jit`. Besides all the filtering and such, one of the other upgrades that's gone into this is that it is smart enough to be able to JIT arbitrary callables, not just Python functions. 

If you really wanted to, you could also instead do something like:
```python
@jax.jit
def invoke(fn, a, b, c):
    return fn(a, b, c)

invoke(fn, x, x, x)
```
which is actually pretty much what `eqx.filter_jit` does under the hood.

**Comment by Honyant** [comment]
Thanks for the detailed explanation! Resolved.
