### ISSUE TITLE
Freeze only some entries in a parameter array?

### ISSUE THREAD

**Issue by leonard-gleyzer** [patrick-kidger/equinox#123]
Hello,

Is it possible to freeze only some entries in a parameter array?

Here is a MWE, where I would like only one entry of a parameter array to update while training, so I'm trying to create a `filter_spec` to do so:

```python
import equinox as eqx

import jax.numpy as jnp
import jax.random as jr


class M(eqx.Module):
    params: jnp.array

    def __init__(self):
        super().__init__()
        self.params = jr.normal(jr.PRNGKey(0), (2,))


module = M()

filter_spec = eqx.tree_at(
    lambda tree: (tree.params[0], tree.params[1]),
    module,
    replace=(True, False),
)
```

However, this causes `TypeError: '_LeafWrapper' object is not subscriptable`.

Is there any way to achieve this?

**Comment by patrick-kidger** [comment]
Not directly like this no; filtering only works at the level of PyTree leaves. Indeed JAX itself doesn't really offer any way to only compute gradients wrt only part of an array anyway.

Probably the best way to accomplish this is either:
(a) compute gradients wrt the whole array, and then set the gradients for the "frozen" parts to zero.
(b) split your array into multiple arrays and compute gradients only wrt the pieces you care about.

**Comment by leonard-gleyzer** [comment]
Makes sense, thank you.

**Comment by arpastrana** [comment]
Which route did you end up going, by the way @leonard-gleyzer?

I am curious since I am also facing a similar situation for a physical simulation where it would be ideal to "freeze" specific elements in an jnp.array for gradient computation. The two options that @patrick-kidger proposed make sense. I am just wondering if you tried both and found one more computationally performant than the other. Thanks!
