### ISSUE TITLE
Updating `operation` in `equinox.nn.Pool` to `static_field`?

### ISSUE THREAD

**Issue by paganpasta** [patrick-kidger/equinox#149]
Hi @patrick-kidger,

Using Pool modules with `jax.jit` raises `TypeError: Argument '<function max at 0x7ffb8ca7b940>' of type <class 'function'> is not a valid JAX type.` 

It can be circumvented by decorating the `forward pass` with `@eqx.filter_jit` instead. 
However, for a uniform behaviour, the `operation` attribute can be defined as `static_field()` to fix this difference. Is this difference intended? 

A script to reproduce the behaviour
```python
from equinox.custom_types import Array

import jax
import jax.random as jrandom
import equinox as eqx
import equinox.nn as nn


class Net(eqx.Module):
  maxp: eqx.Module

  def __init__(self):
      super().__init__()
      self.maxp = nn.MaxPool2d(kernel_size=3, stride=2)

  def __call__(self, x: Array) -> Array:
      return self.maxp(x)


@jax.jit  #breaks
# @eqx.filter_jit  #works
def forward(model, x):
    return jax.vmap(model)(x)

model = Net()
random_image = jax.random.uniform(key=jrandom.PRNGKey(0), shape=(1, 3, 224, 224))
output = forward(model, random_image)
print(output.shape)
```

**Comment by patrick-kidger** [comment]
This intended, and is actually pretty much the purpose of filtering: filtering is used to handle the fact that when treated as a PyTree, your model may have leaves that are not JAX types.

The thing is that we can't unconditionally make callables (like `operation`) a static field, because in principle we may wish to use a learnt callable (i.e. the callable may itself be a PyTree with parameters).

Variations of this come up every now and again, most frequently wrt the activation function of `MLP` (#69, #105, #108). This definitely seems to be the biggest hurdle people have with getting up to speed with Equinox, so I'd welcome thoughts on any way the docs might be improved.

**Comment by paganpasta** [comment]
Thanks a lot for the response.  

Just listing down here few things I think may help (hopefully).

- Currently, there is no indication in the docs as to which `nn.Module`s will not play well with `jax.jit` and which one will require filtering. Every time going through the source code to understand which Module might not work is cumbersome. This information can be highlighted in the doc? 

- Apart from having info in the documentation, a quicker way for a user to know the behaviour can be through adopting a naming convention for Modules? Julia adopts `!` convention for functions performing `in-place` updates (`_` for PyTorch). Maybe `Maxpool2d_` can convey the non-JAX type behaviour for equinox?

- Another idea can be a `check` functionality  which returns a `Sequence` of leaves that will require explicit filtering. Not sure how this will be implemented if possible.

- Wrapping simple/commonly used activations in nn.Modules? #102 Discusses something similar but rather than relying on `Lambda`; simply constructing a `ReLU` with jnn.relu inside `__call__` will work without filtering (increasing user dependency with the lib at the cost of relatively poorer design).
 
- The doc already has an example on filtering. Maybe adding a small filtering component inside the quickstart example can instil to check the types?

**Comment by patrick-kidger** [comment]
So in principle I'd suggest just always using `eqx.filter_jit`. IMO it's basically just an upgrade, feature-wise, compared to `jax.jit`.

I'm not really a fan of the underscore etc. Whether you need to think about filtering isn't really up to e.g. MLP -- as you note someone could use a Module as the activation function, which would work silently.

Regarding introducing `eqx.nn.ReLU` etc, I think the main argument against this so far has been that it introduces the need for filtering earlier in a new user's use of Equinox. (Rather than having them think it's broken later down the line.)

Perhaps part of the answer is to stop using `static_field` in `eqx.nn` -- which I suspect is where folks are copying it from, because it's deliberately obscure in the docs -- whilst accepting that this is a minor (loud) backward compatibility break. I maintain that using this is almost always a mistake, and it's only used in `eqx.nn` for obscure compatibility reasons.

**Comment by paganpasta** [comment]
Thanks for the detailed response, really helps in understanding the workflow! 
Marking it close.

**Comment by carlosgmartin** [comment]
> This intended, and is actually pretty much the purpose of filtering: filtering is used to handle the fact that when treated as a PyTree, your model may have leaves that are not JAX types.
> 
> The thing is that we can't unconditionally make callables (like `operation`) a static field, because in principle we may wish to use a learnt callable (i.e. the callable may itself be a PyTree with parameters).
> 
> Variations of this come up every now and again, most frequently wrt the activation function of `MLP` (#69, #105, #108). This definitely seems to be the biggest hurdle people have with getting up to speed with Equinox, so I'd welcome thoughts on any way the docs might be improved.

@patrick-kidger It might be helpful to add a note under [`equinox.nn.Lambda`](https://docs.kidger.site/equinox/api/nn/composed/#equinox.nn.Lambda) that mentions this and instructs users to use `eqx.filter_jit` instead of `jax.jit` if they get an error of the form `X is not a valid JAX type` when using the latter. (I ran into this issue.)

**Comment by carlosgmartin** [comment]
Also, you mention that
>  I'd suggest just always using `eqx.filter_jit`. IMO it's basically just an upgrade, feature-wise, compared to `jax.jit`.

and in #236 you mention that
> You shouldn't find yourself needing to manually specify what is traced and what is static. 99% of the time this is just determined by the type of each argument. (Arrays are traced, everything else is static.)

Out of curiosity, is there a reason JAX doesn't take this approach by default, for its [transformations](https://docs.kidger.site/equinox/api/filtering/filtered-transformations/)?

**Comment by patrick-kidger** [comment]
Yes, that'd be nice to have in the documentation for `Lambda`. (And perhaps also in the FAQ?) I'd be happy to accept a PR on this if you want to put one together?

As for why JAX doesn't just do filtering by default: I can't speak for the JAX core team, but my impression is that this was a design decision that was just overlooked at the time.
