### ISSUE TITLE
Conversion to tensorflow model?

### ISSUE THREAD

**Issue by rdilip** [patrick-kidger/equinox#210]
Hi,

I'm interested in using equinox for an upcoming project I have, but the model will eventually need to be integrated into a larger tensorflow environment. Is there a recommended way to convert an equinox model into a tensorflow model, so I could do training/experiments with equinox and just convert at the end?

**Comment by patrick-kidger** [comment]
There are tools such [jax2tf](https://github.com/google/jax/blob/main/jax/experimental/jax2tf/jax2tf.py) that would probably apply equally well to Equinox as they would to anything else written in JAX.

In addition you could look into how to use JAX models at inference time -- I believe this is frequently still done using TensorFlow rather than JAX.

In each case I don't think there are any Equinox-specific recommendations -- just treat your Equinox code like any other JAX computation graph.

**Comment by rdilip** [comment]
Okay, that's helpful -- thanks!
