### ISSUE TITLE
Best practice for pytree serialisation with nested classes and leaves as functions

### ISSUE THREAD

**Issue by LouisDesdoigts** [patrick-kidger/equinox#267]
So I just came across the new serialization methods in `0.9.2` which is a really awesome feature. I have a slightly more complex situation where I have `equinox` classes as leaves and leaves that are functions that makes the method perform sub-optimally. 

In essence we have some classes where some leaves are either another `equinox.Module` class or a `None`. Similarly some of the leaves are either functions or `dicts`/`lists` with functions as leaves. Here is a minimal example:

```python
class Foo(eqx.Module):
    a : float
    bar : object

    def __init__(self, bar, a):
        self.bar = bar
        self.a = a

class Bar(eqx.Module):
    fn : callable

    def __init__(self, fn):
        self.fn = fn

bar = Bar(lambda x: x**2)
foo = Foo(bar, 2.)
eqx.tree_serialise_leaves("foo.eqx", foo)
```

---

The first issue is that the `tree_deserialise_leaves` doesn't seem to doesn't seem to be able to load the leaf values if the input pytree leaves are `None`, even when passing in the appropriate `is_leaf` function, ie:

```python
leaf_fn = lambda x: x is None
dummy_foo = Foo(None, None)
new_foo = eqx.tree_deserialise_leaves("foo.eqx", dummy_foo, is_leaf=leaf_fn)

print(new_foo)
> Foo(a=None, bar=None)
```

---

The second issue is the function serialization. Currently the function at leaf `foo.bar.fn` is not serialized and so is overwritten when loading. Example:

```python
dummy_bar = Bar(lambda x: x)
dummy_foo = Foo(dummy_bar, 0.)
new_foo = eqx.tree_deserialise_leaves("foo.eqx", dummy_foo)

print(new_foo)
> Foo(a=2.0, bar=Bar(fn=<function <lambda>>))

print(new_foo.bar.fn(2))
> 2 # print 2, not 4 as expected
```

Looking at the the code it seems like the leaves are iterated over and saved depending on their type, which looks to me like it could be extended to utilize `dill` for function serialization. Obviously because these are user defined functions, there can't be guarantee about the serialization of these functions due to possible global variables etc. However I imagine this could exist as an optional flag to the method with appropriate warnings that it is up to the user to have all serialized function be entirely self-contained. 

---

Furthermore I was wondering if these nested classes could be internally serialized if it the exactly class type at each leaf was known at serialization time? This would allow the 'dummy pytree' (`like` parameter) to be loaded internally when deserializing through some recursion. This obviously wouldn't work with classes defined by users and not in existing packages, but could extend the capabilities. 

I suspect this probably falls outside of the main goals of `equinox` but would be extremely helpful for myself and possibly other users down the line. I'd love to discuss these ideas and potentially build them into `equinox`!

Cheers

**Comment by patrick-kidger** [comment]
Regarding the first issue: this is because the leaves of `like` are checked to determine whether we are loading a Python `bool` / a JAX array / etc. That is, the leaves of `like` must have the same type as what is being loaded. (Moreover if it is an array then they should have the same shape and dtype.)

In this case the leaves are `None`. As this isn't a serialisable type (`bool`/`Array`/etc.) then this is passed through unchanged from `like` (as per [the documentation for `tree_deserialise_leaves`](https://docs.kidger.site/equinox/api/utilities/serialisation/#equinox.tree_deserialise_leaves)).

In passing, you have a separate bug: the tree structure of your `dummy_foo` doesn't match the tree structure of your saved `foo`. The former has a leaf where the latter has a `Bar(leaf)`.

I can see that both of these bugs are easy mistakes to make, though! It would be nice if we could somehow serialise more information, so that we can raise some appropriate errors. E.g. maybe we could serialise the number of leaves, and then check that the number of leaves in `like` is equal? I'm not sure how we'd serialise the type, though. I'd welcome any thoughts/PRs on this.

---

Regarding the second issue: indeed, only certain types are serialised.

Handling this in a generic fashion is pretty much impossible -- there's no good way to serialise+deserialise arbitrary Python objects, although dill does an impressive job -- so I'm disinclined to try to serialise+deserialise functions by default.

If as an end user you'd like to try doing this kind of thing anyway, then this is doable by passing in an appropriate `filter_spec`:
```python
def serialise_spec(f, x):
    if isinstance(x, types.FunctionType):
        ...  # your custom serialisation here
    else:
        return eqx.default_serialise_filter_spec(f, x)
        
def deserialise_spec(f, x):
    if isinstance(x, types.FunctionType):
        ...  # your custom deserialisation here
    else:
        return eqx.default_deserialise_filter_spec(f, x)
        
eqx.tree_serialise_leaves("foo.eqx", foo, filter_spec=serialise_spec)
new_foo = eqx.tree_deserialise_leaves("foo.eqx", dummy_foo, filter_spec=deserialise_spec)
```

---

Regarding serialising class types: right, there's no good way to serialise Python classes. The best you can usually do is to save things like `module = cls.__module__` and `name = cls.__name__`, and then hope that you can later do `getattr(sys.modules[module], name)`. This is essentially impossible to get working reliably, so indeed this falls outside the scope of Equinox.

---

As for what the typical pattern is here: it's pretty common to do something like this:
```python
def main(...hyperparameters..., save_path=None):
    model = Model(...hyperparameters...)
    if save_path is not None:
        model = eqx.tree_deserialise_leaves(save_path / "model.eqx", model)
```
or if you need to save/load the hyperparameters as well then those can usually be saved/loaded as e.g. `save_path / "hyperparameters.json"`.

One thing I would like to add is to make it possible to do:
```python
def main(...hyperparameters..., save_path=None):
    if save_path is None:
        model = Model(...hyperparameters...)
    else:
        model = eqx.filter_eval_shape(Model, ...hyperparameters...)
        model = eqx.tree_deserialise_leaves(save_path / "model.eqx", model)
```
so that one doesn't need to actually initialise the model's parameters just to throw them away; c.f. #259.

**Comment by LouisDesdoigts** [comment]
Ah yes using the `like` pytree as a way to guarantee matching leaf `dtypes` makes perfect sense. Serialising the number of leaves sounds like a good method to help this, I am happy to tinker on this in the background.

Another thing I have realised is the `tree_serialise_leaves` method is blind to `static_fields` (which makes sense), however that data _is_ captured in the `PyTreeDef`. I've had a bit of a look at this class but its down at the XLA level which is well out of my wheelhouse. I was thinking that the full state of the class could be captured if this could be serialised. Full models could then be reconstructed using the serialised leaves and the `PyTreeDef`. This is probably a non-trivial problem though. 

Ah I hadn't realised that the `filter_spec` argument could be used to write custom methods for non-standard leaves, this is very handy. I will see how far this can take me with the other json hyperparameter ideas. 

I'll close this issue for now and re-open it if I come up with things I think could be handy!

**Comment by LouisDesdoigts** [comment]
I've been playing around with this some more and have figured out a rough method to save nested pytree structures. It works by using a `_construct()` method added to each class used to initialize an 'empty' pytree of the same structure with placeholder leaves of the correct type (but not shape). The issue is the arrays of the `like` pytree  have different shape to those that are serialised, so errors are thrown when using `tree_deserialise_leaves`. 

I was thinking a `strict=True` parameter could be added to the `tree_deserialise_leaves` function that can be used to skip the mapping of the `_assert_same` step. This would save a lot of trouble in needing to serialise this meta-data and ensuring that all the `_construct()` methods can specify shapes and dtypes for each parameter.

Let me know if you think this could be a valuable addition and I'll be happy to make a PR.

**Comment by LouisDesdoigts** [comment]
So I've devised a decent method to serialise arbitrary pytree structures as a `json`, along with object types, dtypes/shapes and any other meta data that can be used to reconstruct them when deserialising. It's not elegant and requires the classes to have a clunky `_construct()` method, but it does work. I'm wondering if the `_construct()` method could be avoided altogether from the `equinox` level? I've looked at the `module._ModuleMeta.__new__()` method and I _think_ something like this could be achieved from this class that sets all parameters to `None`, which can then be re-assigned in the deserialisation method and finally re-populated with the `deserialise_tree_leaves` method. 

Let me know if you think this 'empty class constructor' is even possible because I think it would prove to be highly valuable to building a more general serialisation method that doesn't require a `like` pytree.

**Comment by patrick-kidger** [comment]
How does this work? In general one needs to be able to serialise arbitrary Python objects.

**Comment by LouisDesdoigts** [comment]
So the pytree is manually traversed and a dictionary is created for each node (as either a container or leaf) which stores the object type, any children nodes, and meta-data for each leaf (ie shape and dtype for arrays). This nested dictionary is then pickled and the leaves serialised using `tree_serialise_leaves()`

In a new script this is traversed with the relevant modules searched for and imported. The classes are then instantiated (with `_construct()` for custom classes), handling special leaf cases for arrays, Nones etc. This pytree is then passed to `tree_deserialise_leaves()`.

This works but does require the `_construct()` method for classes with is really not ideal, hoping you might have some ideas here! There are still some edge cases that need to be handled (ie static_fields that are arrays for example will not be serialised) but most of these can be solved with a bit of filtering and consideration without any structural changes to the method. 

The benefit of this method is that every internal node is traversed, so errors can be raised for unserialisable objects (ie classes without an `_construct()` method) and warnings can be raised for classes in the `__main__` namespace, leaves that are functions etc.

This would obviously be difficult to make _fully_ general but can be used robustly with packages built on top with a bit of consideration. I've got a working first-pass version up [here](https://github.com/LouisDesdoigts/zodiax/blob/serialisation/zodiax/serialisation.py) that you can check out.

**Comment by patrick-kidger** [comment]
Hmm, I think there's a fair amount that can be tidied up.

- You can probably use something like `cls.__new__(cls)` to instantiate an "empty" class rather than needing a `_construct` method.
- Likewise for things like having a `.set` method, you can probably just use `object.__setattr__(self, name, value)`. Take a look at how Equinox does PyTree unflattening for context on both of the above points.
- Doing a `try-eval-except` seems very dangerous / error-prone to me. I'd recommend using an explicit allow-list of types that you know how to serialise.
- Don't catch `BaseException`.

**Comment by LouisDesdoigts** [comment]
Ah I thought there would be some way to create these empty classes! I would not have thought that this syntax would work since the object are immutable (and honestly I don't really understand _why_ the `object.__setattr__(self, name, value)` works). Either way this is perfect, I really appreciate it!

Yes those try-catch statements were mostly for development purposes and have been removed. I've updated the method to be more rigid to class types and moved it into an experimental module. There are still some rough edges that will be smoothed out as we develop the method on the eco-system we are building on top of equinox/zodiax.
