### ISSUE TITLE
Slightly unintuitive `eqx.nn.Sequential`

### ISSUE THREAD

**Issue by mfkasim1** [patrick-kidger/equinox#32]
My first intuition when working with `eqx.nn.Sequential` (e.g. for a simple MLP) is like below:

```python
import jax
import equinox as eqx

key = jax.random.PRNGKey(0)
key1, key2, key = jax.random.split(key, 3)
module = eqx.nn.Sequential([
    eqx.nn.Linear(5, 10, key=key1),
    jax.nn.log_sigmoid,
    eqx.nn.Linear(10, 2, key=key2),
])
keyx, key = jax.random.split(key, 2)
x = jax.random.normal(keyx, (5,))
y = module(x)
```

However, the code above does not work because of the error: 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/equinox/nn/composed.py", line 124, in __call__
    x = layer(x, key=key)
TypeError: log_sigmoid() got an unexpected keyword argument 'key'
```

So the module has to be slightly modified into:

```python
module = eqx.nn.Sequential([
    eqx.nn.Linear(5, 10, key=key1),
    lambda x, key: jax.nn.log_sigmoid(x),  # adding a thin wrapper
    eqx.nn.Linear(10, 2, key=key2),
])
```

Is this a deliberate choice?
Why not detecting whether a module has `key` in its `__call__` method and then call it appropriately (whether to use `key` or not)?

**Comment by patrick-kidger** [comment]
So this was a deliberate choice, basically just for simplicity/consistency of interfaces.

Detecting that (presumably via `inspect.signature`) sounds like it would be quite fragile. For example what if the layer provided is some sort of `*args, **kwargs`-accepting operation? (Perhaps it's a wrapper for something else.)

For this kind of thing a lot of libraries have some kind of `Lambda` functionality, that would also do the trick here:
```python
class Lambda(eqx.Module)
    fn: Callable[[Any], Any]

    def __call__(self, x, *, key=None):
        return self.fn(x)
```

Maybe it'd be worth adding `eqx.nn.Lambda`? WDYT?

**Comment by mfkasim1** [comment]
`eqx.nn.Lambda` seems too thin for me. Actually having `lambda x, key: fcn(x)` is not that of a big problem. It could just be a bit confusing for newcomers to equinox (like me) because having additional `key` kwarg is unconventional. Maybe a clearer error message in the initialization `eqx.nn.Sequential` would help?
Something like `Module {module_name} has no 'key' in its __call__ method. equinox.nn.Sequential requires the module to be callable with 'key' argument.`

**Comment by patrick-kidger** [comment]
So it's worth noting that one big difference between `lambda` and `Lambda` is that the latter is a PyTree, and therefore we can see any leaves of `fn` if `fn` is also a PyTree. (Rather than having `lambda x, key: fn(x)` as a leaf.) That is, `fn` need not be just a Python callable.

Nonetheless I'm inclined to agree with you -- it feels quite niche to have `Lambda` purely as a helper for `Sequential`.

I'm not sure how strongly I feel about an error message. I think the current one is already pretty clear, and moreover it's easy to debug. If we start introducing cunning machinery based around `inspect.signature` or something then it makes the implementation for `MLP` a bit more convoluted. How strongly do you feel about this?

**Comment by mfkasim1** [comment]
I don't feel strongly on this as well because it is just a little hiccup at the beginning, but once people get used to it, then it is fine.
