### ISSUE TITLE
'filter_custom_vjp' object has no attribute 'def_fwd'

### ISSUE THREAD

**Issue by pablo2909** [patrick-kidger/equinox#413]
Hi,

I'm not sure if I am doing something wrong but I am running this small example and I am getting `AttributeError: 'filter_custom_vjp' object has no attribute 'def_fwd'`:

```python
import equinox as eqx
import jax
import jax.numpy as jnp

def f(x, alpha):
    return alpha * x**2


@eqx.filter_custom_vjp
def squares_norm(x):
    return jnp.sum(x**2)


@squares_norm.def_fwd
def squares_norm_fwd(perturbed, x):
    jax.debug.print("perturbed = {x}", x=perturbed)
    return squares_norm(x), x


@squares_norm.def_bwd
def squares_norm_bwd(residuals, grad_obj, perturbed, x):
    jax.debug.print("residuals = {x}", x=residuals)
    jax.debug.print("grad_obj = {x}", x=grad_obj)
    jax.debug.print("perturbed in bwd = {x}", x=perturbed)
    return  grad_obj


x = jnp.array([2.0])
alpha = jnp.array([5.0])


@eqx.filter_value_and_grad
def F(x__alpha):
    x, alpha = x__alpha
    return squares_norm(f(x, alpha))


F((x, alpha))

```

What could be the problem here ?

jax 0.4.13
jaxlib 0.4.13
equinox 0.10.6

Thank you :)

**Comment by pablo2909** [comment]
I also tried running the following that I found in some test file and I get the same error:

```python
@eqx.filter_custom_vjp
def f(x, y):
    return x + y


@f.def_fwd
def f_fwd(perturbed, x, y):
    return x + y, None


@f.def_bwd
def f_bwd(res, ct, perturbed, x, y):
    return ct


f(jnp.array([1.0]), jnp.array([2.0]))
```

**Comment by patrick-kidger** [comment]
Ah, you've slipped in a crack.
`def_fwd` and `def_bwd` got added in Equinox v0.10.7. That's since revealed itself to have a couple of bugs that I need to tidy up, so I've temporarily switched the default `pip` installation back to v0.10.6 whilst I sort them out. But I think the documentation already lists `def_fwd` and `def_bwd`!

Just use `.defvjp` instead for now. The `.def_{fwd,bwd}` version will become the preferred way to do it in a couple of days, once these bugs are squashed.

**Comment by pablo2909** [comment]
Will do , thank you ! :)
