### ISSUE TITLE
Shortcut for optim.init

### ISSUE THREAD

**Issue by Artur-Galstyan** [patrick-kidger/equinox#441]
Hi Patrick, 

what do you think about having a shortcut for this:

```python
optim.init(eqx.filter(model, eqx.is_array))
```

The initialization of `optim` always trips me up. Maybe having something like

```python
optim = optax.adam(learning_rate)
eqx.init_optim(optim, model)
```

```python
def init_optim(optim: optax.GradientTransformation, model: PyTree):
    return optim.init(eqx.filter(model, eqx.is_array))
```

could be helpful. 

One reason *against* this would probably be having optax as a dependency.

**Comment by patrick-kidger** [comment]
I'm afraid that I'm inclined against this, just because I'd prefer for Equinox to have as small an API surface as possible. That keeps it easy to learn. (Although the API has certainly grown a lot over time.) Even the existence of `eqx.apply_updates` makes me a bit annoyed, actually -- it's just a tree-map over addition, after all!

FWIW this wouldn't need Optax as a dependency though, since it's only explicitly used as a type annotation.

**Comment by Artur-Galstyan** [comment]
Okay, got it. I had thought since there exists `eqx.apply_updates` (and this `init` is kind of related) that you actually wanted these helpers, but turns out it was the other way around 😄. I can fully understand the rational. Closing this then.
