### ISSUE TITLE
Unsupported operand type when running optax optim update

### ISSUE THREAD

**Issue by ma-rv** [patrick-kidger/equinox#458]
Hey, any idea what is causing the following error? Im new to jax, hence sorry for the probably simple question ;)

```
import equinox as eqx
import jax
import optax
import jax.numpy as jnp

model = eqx.nn.Linear(1, 1, key=jax.random.PRNGKey(1))

optim = optax.adam(learning_rate=0.1)
optim_state = optim.init(eqx.filter(model, eqx.is_array))
def loss(x):
    return jnp.mean(model(x))

grads = jax.grad(loss)(jnp.zeros((1)))

updates, opt_state = optim.update(updates=grads, state=optim_state)
```

```
  File "..../lib/python3.9/site-packages/optax/_src/transform.py", line 84, in <lambda>
    lambda g, t: (1 - decay) * (g ** order) + decay * t, updates, moments)
TypeError: unsupported operand type(s) for *: 'float' and 'Linear'
```

**Comment by patrick-kidger** [comment]
When you write `grads = jax.grad(loss)(jnp.zeros((1)))`, you are compute the gradient of the function `loss` with respect to the first parameter -- which in this case is the scalar `jnp.zeros(1)`. So you're computing the gradient with respect to the input `x`, not of the parameters inside `model`!

You probably want something like:
```python
def loss(model, x):
    return jnp.mean(model(x))

jax.grad(loss)(model, x)
```
After that:
- if your `model` includes non-arrays (quite common, e.g. `eqx.nn.MLP`) then you want `eqx.filter_grad` instead of `jax.grad`
- you should make sure to JIT everything for speed.

Take a look at this [CNN example](https://docs.kidger.site/equinox/examples/mnist/) for further introduction. :)

**Comment by ma-rv** [comment]
Thank you! I wonder how I could miss that detail.
