### ISSUE TITLE
Understanding ensembling behaviour

### ISSUE THREAD

**Issue by skylooop** [patrick-kidger/equinox#559]
Hi! I am learning equinox and have question about ensembling. I want to vmap over models and then vmap over data. For example, two models with different weights need to be instantiated and then each model should evaluate on each of input. Currently Im using following code snippet
```
rng = jax.random.PRNGKey(42)
x = jax.random.normal(rng, shape=(5, 2))

@eqx.filter_vmap
def make_ensemble(key):
    return nn.MLP(2,1, 1,1, key=key)

mlp_ensemble = make_ensemble(jax.random.split(rng, 2))

@eqx.filter_vmap(in_axes=dict(model=eqx.if_array(0), x=None))
@eqx.filter_vmap(in_axes=(None, 0))
def evaluate_ensemble(model, x):
    return model(x)

evaluate_ensemble(mlp_ensemble, x) # output should be (2, 5, 1)
```
Output:
```
[[[0.3251164 ]
  [0.3251164 ]
  [0.3251164 ]
  [0.3251164 ]
  [0.3251164 ]]

 [[0.7344204 ]
  [0.7370314 ]
  [0.687357  ]
  [0.8632323 ]
  [0.65112364]]]
```
And for some reason i get same results for different x in batch. Maybe Im missing something? In Flax i get very different outputs, so maybe i dont fully understand how ensembling in equinox works

**Comment by patrick-kidger** [comment]
The code you've written for ensembling is correct.

The reason you're getting the same output is because your MLP is very very small (1 hidden layer of 1 neuron) and uses the ReLU activation function. All of your inputs are hitting the `0` part of the hidden ReLU rather than the `x` part of the hidden ReLU, so the `0.3251154` that you're seeing is the bias of the last linear layer. Make your network larger, or use a bijective activation function, and you'll get different results.

**Comment by skylooop** [comment]
Indeed, thank you!
