### ISSUE TITLE
Feature request to deserialize Modules from their class definitions

### ISSUE THREAD

**Issue by mjo22** [patrick-kidger/equinox#633]
Hello! I have a feature request regarding serialization. I have been writing a package and initially built in serialization functionality using a dataclass serialization scheme. (this isn’t important for this request, but I used the package `dataclasses-json`, see here: https://github.com/mjo22/cryojax/blob/main/src/cryojax/core.py)

I don’t like this solution and am planning on getting rid of it all together in favor of equinox serialization. A feature that I would very much like then is a way to serialize and deserialize `Module`s solely from their class names. In particular, something like

```python
import equinox as eqx

class SomeModule(eqx.Module):
    …


filename = …
eqx.module_serialise(filename, module)
eqx.module_deserialise(filename, SomeModule)
```

This seems to be a bit different than the current serialization functionality, which if I’m not mistaken only serializes leaves and not details of the pytree structure (i.e. fields with `static = True`). I understand this may go against the philosophy of “do not treat Modules differently than any pytree,” and I could reasonably see this feature request being rejected because I’m basically asking for an alternative to pickling, which is not a very jax-y request.

These functions would probably would require another default `filter_spec` that knows how to handle python objects, like strings and perhaps callables. It would probably also, maybe unappealing, require a hacky way of deserializing without calling `__init__`.

**Comment by patrick-kidger** [comment]
IIUC, you're thinking of trying to de/serialise
(a) the JAX built-in pytree types, and
(b) `eqx.Module`s, by treating them as dataclasses. (So that you even pickle static fields -- which are *not* part of the PyTree leaves.)
(c) leaves that are only arrays / ints / global functions / etc.

In this particular case, I think simply directly using `pickle` (or one of its derivatives, like `dill` or `cloudpickle`) may be the correct solution: I think they will already basically handle all of the above except arrays, and I think each of these libraries make it straightforward to add custom de/serialisation behaviour for those.

In particular, I don't think the above uses anything about PyTrees in particular. So indeed I think this is probably out-of-scope for Equinox itself.

**Comment by mjo22** [comment]
This makes sense. I was hoping somehow `tree_at` could be utilized in such a way that would avoid pickling, but I see why this doesn’t make sense.
