### ISSUE TITLE
Not using `filter_jit` produces `None` during backward pass

### ISSUE THREAD

**Issue by neel04** [patrick-kidger/equinox#681]
So I've had this problem a couple times and finally decided to make an issue of it 😝 

Effectively, its just:
```diff
- @eqx.filter_jit
+ @partial(jax.jit, static_argnums=(6, 8))
```
```py
def make_step(model: eqx.Module, # replicated across devices
              x: Array, y: Array, pad_mask: Array, n: Array, k: Array, # Arrays
              optim: Callable, # static
              opt_state: Tuple[PyTree], # cannot be static marked static as tuple
              num_classes: int, # static
              keys: List[PRNGKeyArray]):
    
    loss, grads = compute_loss(model, x, y, pad_mask, n, k, num_classes, keys)
    updates, opt_state = optim.update(grads, opt_state, model)
    
    model = eqx.apply_updates(model, updates)
    
    return loss, model, opt_state
```
Which in theory should work as well as `filter_jit`. But actually yields error:

```py
  File "/Users/neel/miniconda3/envs/react_jax/lib/python3.10/site-packages/optax/_src/transform.py", line 83, in <lambda>
    lambda g, t: (1 - decay) * (g ** order) + decay * t, updates, moments)
TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'
```
In the `optax.optim.update` step. 

More digging, its apparently the `Dropout` layer in the `PyTree`. More specifically, `p` takes `None` presumably after the `eqx.filter` step to obtain the `opt_state`. During the [`tree_map`](https://github.com/google-deepmind/optax/blob/95af789cb7f1d0279f44e143e3207e2e7b4d70d1/optax/_src/transform.py#L80) for the update, eventually moments (`t` becomes `None`).

This problem is always in `Dropout` for some reason, which is weird because its possible the simplest layer.

From the `moments` PyTree:
```py
dropout=Dropout(p=None, inference=None),
```

Whereas the same place in the `updates` PyTree:
```py
dropout=Dropout(p=f32[], inference=None),
```

**The solution** here turned out to use `is_array_like` instead of `is_array` during the `init`.

```py
opt_state = optim.init(eqx.filter(model, eqx.is_array_like))
```

---

I'm curious to understand - why's that `filter_jit` does make it work wo/ `is_array_like`? What's the interplay between `Dropout` and `is_array_like`?

Skimming through the (admittedly complicated for me) code, it seems that `filter_jit` partitions the arguments into hashable and non-hashable, through `eqx.is_array` and return a wrapped + jitted `Module`.

I thought that perhaps, I may have simply missing some static argument - so if I do `eqx.is_array` on all of them, I get:

```py
>>> args = (model, x, y, pad_mask, n, k, optim, opt_state, num_classes, keys)
>>> list(map(eqx.is_array, args))
[False, True, True, True, True, True, False, False, False, True]
``` 

Which seems about as expected, and marked in my `static_argnums`.

---

FYI: This error actually arises as a result of this cool new library, [`scalax`](https://github.com/young-geng/scalax) which can do complicated distributed sharding schemes - like FSDP - with basically just a decorator. It uses a modified version of `jax.jit` behind the scenes, so thats probably why the error arises. However the error can be repro-ed using vanilla `jit`.

Perhaps there's some simple changes the author can make to the lib to make it equinox friendly? :)

**Comment by lockwo** [comment]
It would be beneficial to provide a MVC, I suspect something is going on that is fixable, but it's hard to pinpoint it without a minimal example to test

**Comment by patrick-kidger** [comment]
I think I can explain this.

`dropout.p` is a Python `int` or `float`. When using `jax.jit`, then it now gets promoted to a tracer -- which means that is is now treated dynamically as an array. (And appears in the `updates` PyTree.)

Meanwhile in `optim.init` you're filtering by `eqx.is_array`, so there it is treated statically.  (And is `None` in the `moments` `PyTree. Note that `moment` is part of `opt_state`.)

(In contrast, if you'd used `eqx.filter_jit`, then it would be treated statically both times.)

Your simplest fix is probably the one you've identified, to use `optim.init(eqx.filter(model, eqx.is_array_like))` instead. You could also try adjusting things in some way so that `jax.jit` does not get the opportunity to promote any arraylikes into arrays.

Unfortunately `bool`/`int`/`float`/`complex` are a source of subtle issues like this. In another world we could maybe have designed JAX and Equinox to handle those more carefully, and remove this 'arraylike' category. Alas, we did not.

**Comment by neel04** [comment]
Thanks so much! this explains things a lot. I wonder, would a workaround be for `scalax` to adopt `filter_*` version of everything, or would it simply be easier to (_somehow_) integrate `dropout.p` as an `Array`. The latter definitely is much harder to workaround, as you mentioned, its a core internal issue of JAX/Equinox.

Also, just putting out ideas - doing a `field(static=True)` to enforce staticness on `dropout.p` might be appropriate, and swap with the identity function during `inference_mode`.. might work? or perhaps, easier to just replace all `dropout` leaves with `nn.Identity` 🤔 

None of these solutions are particularly pretty though, and very rough.

**Comment by patrick-kidger** [comment]
I probably wouldn't want to special-case `dropout.p`, as it wouldn't actually help that much -- in particular the `inference` flag would still need handling, but that *has* to remain a non-array that's non-static. (For the sake of `eqx.nn.inference_mode`).

It would certainly be neat if scalax decided to adopt Equinox! FWIW there are many alternative approaches for this issue from a user side, though: we touched on using `eqx.is_array_like` above. You could probably also use [partition and combine](https://docs.kidger.site/equinox/all-of-equinox/#2-filtering) in the usual way for interfacing with any kind of JAX code. A third option is to use `eqx.tree_at` to replace `Dropout(p=0)` with `Identity()`. A fourth option would be to simply write your own dropout layer with the behaviour you prefer. A fifth option might be to use `eqx.tree_at` to replace `p` with `Static(p)`, where
```python
class Static(eqx.Module):
    p: float = eqx.field(static=True)

    def __float__(self):
        return self.p
```
(possibly with a helper to ensure that `__float__` is called)

The above is all generally within the main thesis of Equinox, which is that we should be compatible with, and offer the tools for, being compatible with arbitrary JAX code.

**Comment by neel04** [comment]
I'll try some of those solutions. Thank you so much for providing such a wonderful library! 🔥

**Comment by neel04** [comment]
@patrick-kidger For reference, I was trying to build my transformer using `vmap` instead of layer-by-layer to improve compilation speed, in accordance with the [FAQ](https://docs.kidger.site/equinox/tricks/#improve-compilation-speed-with-scan-over-layers)

And `dropout.p` causes problems there as well 🙃. So effectively, when we pass in the `dynamic_` part of the model to `scan`, at this [point](https://github.com/google/jax/blob/8bf3f47f026d8b8c044fc1de50e26c5f4ca78afd/jax/_src/lax/control_flow/loops.py#L205) in scan we check for the leading dimension for all the `arrays` as dictated by the `filter_spec` used in the `eqx.partition`.

Trouble is, `dropout.p` shows up as an empty array (`dropout=Dropout(p=f32[], inference=None)`) so `.shape[0]` results in a `tuple index out of range` error.

I tried a bunch of different filter specs: `eqx.is_array_like`, `eqx.is_inexact_array_*` etc. but none of them work.

I think rn, having worked with quite a few equinox tools, this is the only sharp edge that's constantly coming back to bite.
What do you think I should do here? Just replace arrays with `ndim == 0` with `None`?

**Comment by patrick-kidger** [comment]
I think the odd bit there is how `dropout.p` is appearing as an array for you. By default it should just be a Python float, and a simple `partition(..., eqx.is_array)` should suffice.

If you need to, then you can also do finer-grained partitions. For example, you can specifically exclude dropout by doing
```python
eqx.partition(layer, eqx.is_array, is_leaf=lambda x: isinstance(x, eqx.nn.Dropout))
```
so that the whole `Dropout` layer is treated as a single object. (And will then fail the `eqx.is_array` check, since of course `eqx.is_array(dropout)` gives `False` -- it's an Equinox module, not a JAX array.) You can then pass it across the `scan` boundary in the usual way for `partition`+`combine`.

(Incidentally CC @knyazer, since this seems to highlight a flaw with our thinking about making `dropout.p` be a NumPy array. It means that existing code with an `eqx.partition(..., eqx.is_array)` might start exploding. Perhaps we should instead introduced `filter_{scan,cond,...}` and recommend using those?)

**Comment by neel04** [comment]
> I think the odd bit there is how dropout.p is appearing as an array for you.

That's what this issue thread was about 😉 in the `updates` PyTree when doing a backward pass, it was promoting that `float` to a tracer during JIT compilation. That's why it was "fixed" when filtering by `eqx.is_array_like` instead of vanilla `eqx.is_array`.

Specifying the `is_leaf` worked perfectly - I totally forgot that was a thing, I thought I'd have to do some ugly surgery to fix it. Thank you so much!

**Comment by knyazer** [comment]
@patrick-kidger, I think the idea of doing filtered scans/conds is the thing we were discussing at some point already :)

I was satisfied with the equinox.internal ops, and, while modifying them to include dropout as an edge case is a way, maybe it's nicer to have a generalizable way to do that? Like,
```
p: float = eqx.field(differentiable=True)
```
And add a new filter ```is_differentiable```?


The burden of filtering is on the third party library (that is dependent on equinox), which should mark fields with differentiable/non-differentiable, and the user of this third-party library will just have to use ```is_differentiable``` instead of ```is_array```. So this _differentiability_ is just a flag for the end-user convenience. And I like this more than having exceptions in the very general filter_* functions..

**Comment by patrick-kidger** [comment]
This kind of `is_differentiable` stuff has been mooted before, actually! (Waaaay back in the early days of Equinox.) It turns out that it doesn't work. The main isue is that the `differentiable=True` is information owned by the `Module`, *not* the field `p`. There's no way to access that during tree-mapping.

(As another issue, given an `x: tuple[float, float]`, there's no way to mark that one of them may be differentiable and another is not.)

---

@knyazer -- what this *has* started me thinking about though, is something like the following: Equinox modules automatically detect static parts of their fields, and wrap them in something like our existing `equinox._module.Static` object. So the result will be to (a) automatically have all static fields hidden from tree-mapping, so that we are out-of-the-box compatible with `jax.jit` etc, but crucially (b) _still have `dropout.p` be a part of the tree structure_. So something like `eqx.tree_at(lambda d: d.p, dropout, ...)` would still work.

That is, the difference from the last time I proposed something like this is that now the static-ness is owned by the wrapping `Static` module, rather than by the `Dropout` module itself.

We'd need to find a way to unwrap the static object before using it -- as part of `Module.__getattr__`? And I'm not convinced that this doesn't bump into other unpleasant edge-cases. But if it *does* work, then it would be a way to get autostatic behaviour for everyone for free.

Alternatively, if it doesn't work in general, maybe we introduce this just for `Dropout`. Minor risk of a compatibility break since we own the whole object, and a way to fix this annoying intersection-of-edge-cases.

**Comment by neel04** [comment]
Personally, I find most of the things about jax/equinox intuitive to reason about. But I feel the PyTree `differentiable/non-differentiable` shenanigans really spoil it for newcomers coming from PyTorch, who aren't used to this way of thinking.

Like recently I wanted to freeze and unfreeze some parameters in the middle of the training (at some predetermined training step) but modifying the `filter_spec` caused a `None` which leads back to this exact issue in the `optim.update` step.. 🫠

I realize that a lot of this has to do with how jax works under the hood, but if equinox can offer some tools to soften the punches then that would be greatly appreciated!

**Comment by knyazer** [comment]
@neel04: I will try to implement the solution proposed by Patrick in #684 (or an alternative PR) in a few days; this hopefully will allow us to ignore the dropout corner case in a generalizable fashion, while also bringing us closer to a shiny future of Equinox modules being compatible with jax operations without filtering.

I also support making the discussions tab, though I believe we currently use issues as a sort of documentation of questions. Your example, on the other hand, could go into the documentation as an "Advanced functionality" of some sorts. But discussions is indeed a good intermediate place to store this kind of stuff.
