### ISSUE TITLE
Callables not marked static prevents dynamic call

### ISSUE THREAD

**Issue by NeilGirdhar** [patrick-kidger/equinox#865]
As already discussed in #842, I'm now hitting a problem whereby I'm trying to use Equinox's MLP module in dynamic calls (in this case to vmap), but the activation functions are not marked as static, and are not dynamic.  As illustrated in this opaque error:
```
  File "/home/neil/src/cmm/cmm/structure/rl/inference.py", line 171, in _set_up_inference
    model_configurations = vmap(self.model_without_weights.dummy_configuration,
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Cannot interpret value of type <class 'jax._src.custom_derivatives.custom_jvp'> as an abstract array; it does not have a dtype attribute
--------------------
```

Would it be okay to wrap the default activation values as described [here](https://github.com/patrick-kidger/equinox/issues/842#issuecomment-2344233917)?

Or perhaps, just provide a generic wrapper for any callable, such as:
```python
class StaticCallable(eqx.Module, Generic[P, R]):
    f: Callable[P, R] = eqx.field(static=True)

    def __call__(self, *args: P.args, **kwargs: P.kwargs) -> R:
        return self.f(x)

@jit
def f(m: MLP, /): ...

mlp = MLP(3, 2, activation=StaticCallable(jax.nn.relu))
f(mlp)  # Won't crash!
```
This could even be exported as `eqx.StaticCallable`?  (If not, I'll probably copy it into my tjax package since I would need to use it with Equinox.

**Comment by patrick-kidger** [comment]
I've deliberately avoided doing this in favor of instead providing `eqx.filter_{...}` transformations.

So I think this is better placed in tjax instead. :)

**Comment by NeilGirdhar** [comment]
Right, I noticed that.  I haven't totally bought into switching all of my calls (`jit`, `vmap`, `grad`, `hessian`, etc.) into the filter equivalents.  So, unless I do that, there's no way to use the Equinox modules (e.g., `MLP`).  This is because the default values for the various callables need to be filtered out of all calls.

I wasn't suggesting the box class as a workaround (since it's not).  I was suggesting that Equinox modules box all of the default values for their callables.  I realize that adds complexity you don't want since you're in the habit of using the filter functions.

I guess my options then are either to accept using the filter functions everywhere, or else do some kind of tree-map where I replace the callables with boxed versions of callables.  Something like:
```
model = fix(eqx.nn.MLP(...))
```
where `fix` does something like `jax.tree.map(lambda x: Box(x) if not is_array(x) else x, model)`.

That seems more complex than the filter functions though.  I guess I'll switch to the filter functions then and reopen this with some new ideas if there's a problem.

**Comment by patrick-kidger** [comment]
Ah, right. Yeah, we've considered that approach:

https://github.com/patrick-kidger/equinox/pull/800#issuecomment-2322214624

It has some issues, however:

https://github.com/patrick-kidger/equinox/pull/800#issuecomment-2322284013

**Comment by NeilGirdhar** [comment]
> It has some issues, however:

Right, but that issue wouldn't affect the fix idea since I would only call `fix` after the module is constructed.

Incidentally, I wanted to share some further thoughts I had about this and get your opinion.  I think the reason that I'm so reluctant to take up Equinox's `filter_` functions is that it's a further step into the Equinox ecosystem.  I used to use Haiku, and then I switched to Flax when Haiku essentially died.  The from Flax, I switched to Flax's NNX when I decided I liked its design better.  Finally, I switched from NNX to Equinox, when decided that your design is even more elegant

The problem is that each of these switches takes around a week.  This is why I'm reluctant to rely on peculiarities of a particular system.  If I have to "move" again, I don't want to spend all my time "packing".

One nice thing about the switch to Equinox was that the modules declare the no-init members as dataclass fields, whereas with Flax, I wasn't careful to do that.  I think this made the code easier to read.  And Equinox forced me to do this.

One of the other issues with the filter system is that it seems that the examples tend to make no distinction between constant (with respecto to optimization) and static (with respect to compilation).  All of the constants tend to be Python floats, integers, etc.  These are static.  It's nice that that works out.  In practice, it can be beneficial for constants to be dynamic:
- it prevents recompilation if you want to run the program again with different constants, and
- it may (please correct me if you know better) prevent host-GPU transfers if the constants are stored in on-device arrays.  (I'm not sure about this, but I'm desperate trying to optimize slow programs, and I know you have quite a bit of experience there.)

From my perspective, it would be nice if Equinox would box the callables to mitigate coupling, but I'm not going to push on this.  I'll box them with a tree-map.

Still, there is an issue with marking dynamic leaves as constant (with respect to optimization).  What I have been doing is boxing them in a special `Constant` box, and then it's easy to filter them out.  However, this won't help me if I want to use an Equinox model and need one of that model's parameters to be constant.  I wonder what you think of setting attributes on a Jax Array for this purpose?  E.g.,
```python
some_constant = jnp.asarray([2.0, 3.0])
some_constant._is_constant = True
model = Model(...., some_constant, ...)
weights = eqx.filter(model, lambda x: getattr(x, '_is_constant', False))  # Will filter out some_constant.
```
Seems a bit flimsy, but at least `some_constant` can still be used with Equinox modules.

**Comment by patrick-kidger** [comment]
> Right, but that issue wouldn't affect the fix idea since I would only call fix after the module is constructed?

You do still end up with a wrapper type (either a global `Fix` or leaf-level `Box`es, depending on your implementation.) So the natural tree structure is still being messed with. (I agree that the `__init__`-time problem can be worked around.)

> The problem is that each of these switches takes around a week. This is why I'm reluctant to rely on peculiarities of a particular system.

Yup, this makes complete sense. I 100% sympathise with wanting this / I have had to do battles in this direction before myself.

Something you might find interesting on this point. Most other equivalents are frameworks, not libraries. That is to say something like Haiku and Flax are mutually incompatible, so if you make one choice then you're essentially blocked out from using the other. In contrast, Equinox avoids this by just using pytrees all the way down. So one can use Equinox alongside any pretty much other valid JAX code. There's no new abstractions; in particular the 'module' type is not in any way privileged.

(Not that I think I need to sell you on Equinox! But I thought you'd find it interesting to see how this has always been a design goal.)

> One of the other issues with the filter system is that it seems that the examples tend to make no distinction between constant (with respecto to optimization) and static (with respect to compilation).

Right, so this is actually another design point for Equinox. Filtering is expressed at the point-of-use with the `jit`/`grad`/etc, rather than being expressed in the pytree structure (which as a point of contrast is what `torch.tensor(..., requires_grad=...)` does).

The reason for this is the extra decoupling: if someone comes along with a brand-new transform, then it's still possible to express how a pytree should behave with respect to that, rather than needing to reach in and adjust the pytree definition somehow.

Such idealism aside, as a practical matter: I think of static-or-not (wrt compilation) as being what the array-or-not choice really expresses. the constant-or-not (wrt optimization) is something that can/should be expressed through `jax.lax.stop_gradient` instead.

> I wonder what you think of setting attributes on a Jax Array for this purpose?

JAX arrays did not use to support monkey-patching on additional attributes, which made anything of this form impossible.

That said, I have just tested this on latest JAX (0.4.33) and it seems like this has changed. I'm not sure if this is intentional -- do you know any more?

**Comment by NeilGirdhar** [comment]
> leaf-level `Box`es, depending on your implementation.) So the natural tree structure is still being messed with.

Right, you got it: I'm using leaf-level `Box`es and I also don't like that the natural tree structure is being messed with.

> JAX arrays did not use to support monkey-patching on additional attributes, which made anything of this form impossible.
> 
> That said, I have just tested this on latest JAX (0.4.33) and it seems like this has changed. I'm not sure if this is intentional -- do you know any more?

No, unfortunately.  However, I'm reluctant use additional attributes unless these attributes are blessed by the Jax team.  I feel like it would be a better solution than my leaf-level boxes.  Don't you think?  It preserves the tree structure and makes easy to filter on.  Maybe it could be possible to inherit from `jax.Array` somehow and add the `flags: dict[str, Any]` member.  As long as it exposes the right interface, the Jax code will have no idea.  So it could be as simple as:
```python
def with_flags(x: Array, /, **kwargs) -> Array: ...

learn_rates = with_flags(jnp.asarray([1.0, 2.0]), constant=True)
```

> In contrast, Equinox avoids this by just using pytrees all the way down. So one can use Equinox alongside any pretty much other valid JAX code.

I love the efforts that you've made towards this goal.  It's one of the many ways in which Equinox really excels.   But when you say library, do you mean only the functions `partition`, `filter`, etc.?  Because I feel like this Github issue highlights the way Equinox modules are not portable: they rely on being used with `filter_*` functions rather than ordinary Jax functions.   If you boxed the default values, then this restriction would be lifted and more of Equinox would fit within the rest of the Jax ecosystem.  What do you think?

> (Not that I think I need to sell you on Equinox! But I thought you'd find it interesting to see how this has always been a design goal.)

Yes, I love that goal.

> The reason for this is the extra decoupling: if someone comes along with a brand-new transform, then it's still possible to express how a pytree should behave with respect to that, rather than needing to reach in and adjust the pytree definition somehow.

Could you expand on this a little bit?  I'm not sure what this means or how it fits?

> Right, so this is actually another design point for Equinox. Filtering is expressed at the point-of-use with the `jit`/`grad`/etc, rather than being expressed in the pytree structure (which as a point of contrast is what `torch.tensor(..., requires_grad=...)` does).

Right, I think we both agree that `requires_grad` is bad design.  Being able to manipulate trees with filter/partition is great design because it gives you a huge amount of control.  But I don't need to sell you on your own design :laughing: 

> Such idealism aside, as a practical matter: I think of static-or-not (wrt compilation) as being what the array-or-not choice really expresses. the constant-or-not (wrt optimization) is something that can/should be expressed through `jax.lax.stop_gradient` instead.

I don't see things that way.   Let's try to analyze this through the lens of _separation of concerns_.  A method on a module (typically `__call__`) is just a forward transformation from the module's parameters and inputs to outputs.  Yes, it may use stop gradient, but in general, it's job is to just produce results.

On the other hand, you may want to hold different parts of the model fixed at different times.  For example, maybe you'd like to do feature learning in one phase, and then learn a mapping from one set of features to the other in the second phase.  Wouldn't it make more sense to separate out this two-phase approach to a higher level that is concerned with that?  At that higher level, it could simply do `equinox.partition` with the filter it wants to isolate the parameters that need to change.  Contrast this with trying to do the two-phase approach by somehow engineering various conditional stop-gradient calls inside module-methods.  I feel like this is unnecessary coupling.

Even from a compilation efficiency and elegance point of view, consider the steps of optimization:
- `equinox.partition` the model into `model_weights` and `model_without_weights`
- create a optax gradient-state for the model-weights
- take the gradient of the loss function with respect to the model weights
- run the optax update using this gradient and the gradient state to produce an updated gradient
- apply the updated gradient to the model weights

I feel like I intuitively want these objects to be as small as possible: model-weights, gradient-state, and gradient.  And that will be achieved if the partitioning is the thing that decides which things are constant with respect to optimization.  And this brings us back to one reason I'm using Equinox in the first place: I really like `equinox.partition`.  (Incidentally `equinox.Module` is well-designed too.  These two things sold me on Equinox.)

**Comment by patrick-kidger** [comment]
> I feel like it would be a better solution than my leaf-level boxes. Don't you think? It preserves the tree structure and makes easy to filter on.

So the thing that we'd really need is for this to be propagated through JIT, grad etc. transforms:
```python
> import jax
> @jax.jit
  def f(x):
      print(x.foo)
> x = jax.numpy.array(1)
> x.foo = 2
> f(x)
# AttributeError: DynamicJaxprTracer has no attribute foo
```
I suspect the recent mutability is probably an unintentional oversight.

> Equinox modules are not portable: they rely on being used with filter_* functions rather than ordinary Jax functions.

I disagree. The same `filter_*` arises if you have any pytree containing not-arrays: you bump into the same issue with a list `[some_array, jax.nn.relu]` for example. Modules are nothing more than pretty ways to create pytrees.

If you have control over your modules then you can arrange for every not-array to be static and then the usual `jax.jit` etc operations work as expected. If you don't have control over them then you may need to do something else, in the exact same way as you'd need to if someone passed you `[some_array, jax.nn.relu]` and told you to JIT it.

> Could you expand on this a little bit? I'm not sure what this means or how it fits?

If someone defines a new transform (unusual, but it does happen), then how should the pytree interact with that transform? If the definition of that is baked into the pytree then I'd struggle to combine a pytree from one third party with a transform from a different third party.

> I don't see things that way. Let's try to analyze this through the lens of separation of concerns. A method on a module (typically __call__) is just a forward transformation from the module's parameters and inputs to outputs. Yes, it may use stop gradient, but in general, it's job is to just produce results.

Right, I understand what you're saying. And it's exactly this kind of thinking which motivates Equinox's preference for filtering at transform time. The `jax.lax.stop_gradient` is just the 'simple pragmatic' solution for when you control both pytree and transform and have are in the 95% use case that it gets the job done.

Anyway, as for the problem you're describing -- if you want to clearly mark which group that an array is part of, then the best solution is to put every array inside a wrapper class. Here's an example of the kind of thing I'm talking about, where we apply a custom operatation to all 'marked' arrays:

https://docs.kidger.site/equinox/tricks/#custom-per-parameter-behaviour

You could likewise imagine partitioning based on such markers. (And if necessary unwrapping it with a tree-map afterwards, so that the calling code doesn't need to know about the presence of your wrapper.)

**Comment by NeilGirdhar** [comment]
> So the thing that we'd really need is for this to be propagated through JIT, grad etc. transforms:

Oh, right.  Okay we can forget that then.

> I disagree. The same `filter_*` arises if you have any pytree containing not-arrays: you bump into the same issue with a list `[some_array, jax.nn.relu]` for example. Modules are nothing more than pretty ways to create pytrees.

Yes, but I don't expect a list of callables to be "dynamic" (passable to a jit, etc.) I do expect modules to be dynamic.  I guess you don't share that expectation.  I also don't remember having this problem with Flax.

The cost of meeting that expectation is boxing default value callables.

> if you want to clearly mark which group that an array is part of, then the best solution is to put every array inside a wrapper class. 

Right, that's what I'm doing.

> You could likewise imagine partitioning based on such markers. (And if necessary unwrapping it with a tree-map afterwards, so that the calling code doesn't need to know about the presence of your wrapper.)

Right.
