### ISSUE TITLE
filter_vmap doesn't allow in_axes as a vmapkwarg

### ISSUE THREAD

**Issue by jvmncs** [patrick-kidger/equinox#87]
Hi, love the idea for the library! I was recently converting a canonical example from stax to equinox and found a discrepancy with what I expected from the `**vmapkwargs` parameter in `eqx.filter_vmap`. In particular, the wrapper from `filter_vmap` is not respecting that the user might pass `in_axes` as part of `**vmapkwargs`, as evidenced by [this minimally-reproducing gist](https://gist.github.com/jvmncs/b2d91fce5f12f01a8f908debbee5622c). After a quick look through the code, the same might be true of `out_axes` and also for `filter_pmap`.

I've traced the TypeError to how `_VmapWrapper` constructs the `in_axes` argument to `jax.vmap`; one fix would be a matter of adding something like 
```python
in_axes = __self._vmapkwargs.pop("in_axes", None)
in_axes = in_axes or _resolve_axes(
    [...]
)
```
[here](https://github.com/patrick-kidger/equinox/blob/9341767b6c8bad4c7a7c89d89c70e1b3133a3e2f/equinox/vmap_pmap.py#L138) before passing `**self._vmapkwargs` to `jax.vmap` later on.

I honestly haven't fully grokked the meaning of some of `filter_vmap`'s kwargs; maybe this is its intended behavior? If so, would appreciate a clarification on what I'm doing wrong by trying to supply a value for `in_axes` to it.

Thanks!

**Comment by patrick-kidger** [comment]
Yep, this is expected behaviour. The purpose of the "filter" in "filter_vmap" is that it constructs `in_axes` and `out_axes` for you in a smart / more-controllable way. (Through its arguments `default`, `args` etc.) So it doesn't make sense to try and pass these separately.

If we're lacking a nice error message explaining this then I'd be happy to accept a PR on this. (`filter_jit` actually already has something similar for `static_argnums`.)

If you just want to translate stuff over in a mechanical way then passing `args=in_axes` and `out=out_axes` should work.
